function data = cen_readTMSi(filename)
% Reads .poly5 data and convert it to a .mat file format
%   that can be read by Fieldtrip

%% Parameters
EEG_CH      = 1:64; 
ECG_CH      = 65;   % Eletrocardiogram channel
EOG_VERT_CH = 66;   % Corner of eyes
EOG_LAT_CH  = 67;   % Above and below right eye
MRKR_CH     = 73;   % Trigger channel
LABELS      = {'Fp1','Fp2','F3','F4','C3','C4','P3','P4',...
    'O1','O2','F7','F8','T7','T8','P7','P8',...
    'Fz','Cz','Pz','Iz','FC1','FC2','CP1','CP2',...
    'FC5','FC6','CP5','CP6','TP9','TP10','AFz','FCz',...
    'F1','F2','C1','C2','P1','P2','AF3','AF4',...
    'FC3','FC4','CP3','CP4','PO3','PO4','F5','F6',...
    'C5','C6','P5','P6','AF7','AF8','FT7','FT8',...
    'TP7','TP8','PO7','PO8','Fpz','CPz','POz','Oz',...
    'ECG','HEOG','VEOG','Marker'}';

%% Convert data from .Poly5
temp    = tms_read(filename);

%% Create fieldtrip-friendly format
channels        = cat(2,EEG_CH, ECG_CH, EOG_VERT_CH, EOG_LAT_CH, MRKR_CH);
data.trial      = {cat(1,temp.data{channels})}; % This is the actual data
data.fsample    = temp.fs; %frequency sampling rate 
data.time       = {(1:size(data.trial{1},2))/data.fsample};
data.label      = LABELS;
    
% Header
data.hdr.Fs             = temp.header.FS;
data.hdr.nChans         = length(channels);
data.hdr.nSamples       = temp.header.NumberOfSamplePeriods;
data.hdr.nSamplesPre    = 0;
data.hdr.nTrials        = 1;
data.hdr.label          = data.label;
data.hdr.chantype       = {'EEG','EEG','EEG','EEG','EEG','EEG','EEG','EEG',...
    'EEG','EEG','EEG','EEG','EEG','EEG','EEG','EEG',...
    'EEG','EEG','EEG','EEG','EEG','EEG','EEG','EEG',...
    'EEG','EEG','EEG','EEG','EEG','EEG','EEG','EEG',...
    'EEG','EEG','EEG','EEG','EEG','EEG','EEG','EEG',...
    'EEG','EEG','EEG','EEG','EEG','EEG','EEG','EEG',...
    'EEG','EEG','EEG','EEG','EEG','EEG','EEG','EEG',...
    'EEG','EEG','EEG','EEG','EEG','EEG','EEG','EEG',...
    'ECG','EOG','EOG','Marker'}';
data.hdr.chanunit       = {'uV','uV','uV','uV','uV','uV','uV','uV',...
    'uV','uV','uV','uV','uV','uV','uV','uV',...
    'uV','uV','uV','uV','uV','uV','uV','uV',...
    'uV','uV','uV','uV','uV','uV','uV','uV',...
    'uV','uV','uV','uV','uV','uV','uV','uV',...
    'uV','uV','uV','uV','uV','uV','uV','uV',...
    'uV','uV','uV','uV','uV','uV','uV','uV',...
    'uV','uV','uV','uV','uV','uV','uV','uV',...
    'uV','uV','uV','V'}';

% info not crucial to data.hdr included below
data.hdr.measurementdate        = temp.measurementdate;
data.hdr.path                   = temp.path;
data.hdr.filename               = temp.filename;
data.hdr.measurementtime        = temp.measurementtime;
data.hdr.measurementduration    = temp.measurementduration;

